version: "3"
services:
  prom:
    image: prom/prometheus:v2.1.0
    volumes:
     - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    network_mode: "host"
    ports:
     - 9090:9090
    depends_on:
     - exporter
     - cloudprober

  cloudprober:
    image: cloudprober/cloudprober
    network_mode: "host"
    ports:
     - "9313:9313"
    volumes:
      - ./config/cloudprober-singletarget.cfg:/etc/cloudprober.cfg

  exporter:
    image: prom/node-exporter:latest
    network_mode: "host"
    ports:
     - "9100:9100"

  grafana:
    image: grafana/grafana
    network_mode: "host"
    ports:
     - "3000:3000"
    depends_on:
      - prom